### ISSUE TITLE
Facebook force close

### ISSUE THREAD

**Issue by akoul** [privly/privly-android#51]
On using the facebook integration, I noticed the following bugs:

1) Some of the chatheads names are wrongly adressed to my account where as originally they are addressed to some other person. ( I can post the screenshot if required)

2) Opening a chat head in which i had sent a test privly message(using chrome extension) to myself caused the app to force close.
Here's the logcat error : 

1969-1969/ly.priv.mobile E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: ly.priv.mobile, PID: 1969
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setTitle(int)' on a null object reference
            at ly.priv.mobile.gui.fragments.ShowContentFragment.onCreateView(ShowContentFragment.java:74)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by vshivam** [comment]
I _think_ I have already fixed the setTitle() issue. 

Updated here : https://github.com/privly/privly-android/blob/master/src/main/java/ly/priv/mobile/gui/fragments/ShowContentFragment.java#L73

**Comment by akoul** [comment]
Force closing of app is resolved by this. However, the anomaly in ChatHeads is still there according to me. In some of the chatheads, my name is shown instead of the person with whom the chat has been done.

**Comment by vshivam** [comment]
Yep. That needs to be fixed.

**Comment by akoul** [comment]
What could be the possible cause of this issue according to you?

**Comment by vshivam** [comment]
You probably need to look in this class : https://github.com/privly/privly-android/blob/master/src/main/java/ly/priv/mobile/grabbers/FaceBookGrabberService.java

**Comment by akoul** [comment]
I'll see if I can solve the bug and let you know.
